Fix a couple of javascript issues
The one in new_main.php caused:

 [ERROR - 2018-10-13T05:32:18.898Z] Session [d9562850-cea8-11e8-8217-37d1863df633] - page.onError - msg: TypeError: undefined is not a function (evaluating 'jQuery('#keyword').autocomplete({'minLength':'2','source':[]})')

[ERROR - 2018-10-12T07:35:29.076Z] Session [6380d4c0-cdf1-11e8-b5ec-67db5ae89842] - page.onError - msg: TypeError: undefined is not a function (evaluating '$("#btnCreateAccount").tooltip({'placement': 'left'})')

the one in new_datasetpage.php caused:

[ERROR - 2018-10-12T07:35:29.076Z] Session [6380d4c0-cdf1-11e8-b5ec-67db5ae89842] - page.onError - msg: TypeError: undefined is not a function (evaluating '$("#btnCreateAccount").tooltip({'placement': 'left'})')