Fix for the error during vagrant provision where git command failed to connect with github.com
the error message says:

```
error:  while accessing https://github.com/yiisoft/yii.git/info/refs

fatal: HTTP request failed
```

ssh-ing into the box and running ``GIT_CURL_VERBOSE=1 git ls-remote "https://github.com/yiisoft/yii.git"``

shows an SSL error (NSS error -12190).

it turned out that github turned off some SSL/TLS protocols yesterday
(See: https://github.com/blog/2507-weak-cryptographic-standards-removed)

and the Centos 6.7 box  used here don't support well the TLSv1.2 protocol that's now mandated by github.

The problem is resolved by force upgrading openssl and curl during provisioning but before call to cookbook  yii_framework command
and only for redhat platform. Using  "package" Chef command doesn't work, i have to use yum_package and flush the yum repos cache beforehand.

(cherry picked from commit e801bea7a0af93ecb046183ac0d76fcbb6cee085)