Fix to out of shared memory error by setting max_locks_per_transaction
When running on my local dev:

./ops/scripts/setup_devdb.sh production_like

I got this error:

Exception: CDbCommand failed to execute the SQL statement: SQLSTATE[53200]: Out of memory: 7 ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.

So I add another configuration to postgres command to implement the suggested hint.