while implementing unmerging of merged authors as part of #49, I had the following test error:
CDbException: Column name must be either a string or an array.

Which indicates that a database table is missing a primary key. In this case, it was author_rel that didn't have a primary key index set up in postgresql.