Disable yii debug on staging to fix to a php/yii error
ReflectionException: Class yii\debug\Module does not exist in /app/vendor/yiisoft/yii2/di/Container.php

because it depends on yii2-gii which I've added only as a dev dependencies.
Will try to keep it a dev dependencies so will attempt to turn off the dependencies